### PR TITLE
Use kubelet 1.10.X for release-1.10 CI

### LINKED ISSUE #294: Create a release-1.10 branch
@Random-Liu @feiskyer @yujuhong wdyt?

cc: @umohnani8

### PR DESCRIPTION
**Pull request by feiskyer**
Fixes #294 

Depending on https://github.com/kubernetes/kubernetes/pull/63387.

### CODE REVIEW

**Comment by Random-Liu** [comment]
@feiskyer Should we only cherrypick this to 1.10 branch?

**Comment by feiskyer** [comment]
@umohnani8 Oops, sent to wrong branch. Reset to release-1.10 branch now.

**Comment by feiskyer** [comment]
@Random-Liu Right, we should cherry-pick the fixes to 1.10, filed https://github.com/kubernetes/kubernetes/pull/63387 for it

**Comment by Random-Liu** [comment]
@feiskyer The error is caused by https://github.com/kubernetes/kubernetes/commit/cfcf9d8511c5c3542a25dc9f430f40cddaeb5f61, which is only in HEAD.

Let's skip that test in 1.10. I just mean that we should not skip it in HEAD.

**Comment by Random-Liu** [comment]
@feiskyer I feel like we should cut branch from v1.0.0-beta.0

**Comment by feiskyer** [comment]
@umohnani8 Still need another approval now

**Comment by umohnani8** [comment]
@feiskyer great! Looks like https://github.com/kubernetes/kubernetes/pull/63387 got merged.
LGTM

**Pull request merged**
