### PR TITLE
share logs with kubelet

### LINKED ISSUE #169: crictl logs should share code from kubelet.
Currently, we copy all the code from kubelet.

We should make the code in kubelet to be a CRI log parsing library. And import the library in `crictl`.

### PR DESCRIPTION
**Pull request by yanxuean**
fix #169  #177
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>

### CODE REVIEW

**Comment by yanxuean** [comment]
@feiskyer @random-liu

**Comment by yanxuean** [comment]
ptal

**Comment by yanxuean** [comment]
@feiskyer 
I can.
Can you tell me the reason?

**Comment by feiskyer** [comment]
For better tracking and understand the commits histroy.

**Comment by yanxuean** [comment]
@feiskyer 
OK. thanks :)

**Comment by feiskyer** [comment]
@yanxuean Maybe I'm not clear. I mean two commits in this PR, one is vendor and the other is calling new methods.

**Comment by yanxuean** [comment]
I misunderstand. I modify it.

**Comment by yanxuean** [comment]
@feiskyer @Random-Liu   PTAL

**Pull request merged**
