### PR TITLE
Add logs command for crictl

### LINKED ISSUE #88: crictl: add logs command

### PR DESCRIPTION
**Pull request by heartlock**
Closes #88
@feiskyer Ready for review!

### CODE REVIEW

**Comment by heartlock** [comment]
Update cri version in this pr, cri test case may need to change. @xlgao-zju Please have a look.

**Comment by xlgao-zju** [comment]
Will try to fix this...

**Comment by Crazykev** [comment]
CI failed due to bug in dockershim, open https://github.com/kubernetes/kubernetes/pull/45808 for this.

**Comment by xlgao-zju** [comment]
CI failed because of [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/libdocker/kube_docker_client.go#L385), will wait for [kubernetes/kubernetes#45808](https://github.com/kubernetes/kubernetes/pull/45808).

**Comment by feiskyer** [comment]
CI still failed:

1. Panic:

image

2. Log test

image

**Comment by xlgao-zju** [comment]
@feiskyer travis is happy now. :)

**Comment by heartlock** [comment]
something wrong yet ...

**Comment by heartlock** [comment]
@feiskyer Fixed!

**Comment by feiskyer** [comment]
@heartlock Would you like also add logs path to frakti?

**Comment by heartlock** [comment]
@feiskyer  Of course !

**Comment by feiskyer** [comment]
@heartlock Thanks.

**Pull request merged**
