### PR TITLE
Add networking test

### LINKED ISSUE #17: critest: DNSOptions, PortMapping and IP

### PR DESCRIPTION
**Pull request by xlgao-zju**
close #17 

Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>

### CODE REVIEW

**Comment by Random-Liu** [comment]
I think the problem is that you should not create container with empty linux configuration.

We point the container to the infra container [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/security_context.go#L162).

However, if the LinuxConfiguration is empty, dockershim will skip all those config steps directly, see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_container.go#L147-L166).

**Comment by xlgao-zju** [comment]
Yes, I think empty LinuxConfiguration will cause creating pod to fail, when I use cni. 
The error like this.
```
NetworkPlugin cni failed to set up pod \"PodSandbox-for-create-test-77c938c8-13b4-11e7-b51d-4ccc6a538d8b_e2e-cri-namespace77c9390f-13b4-11e7-b51d-4ccc6a538d8b\" network: container veth name provided (eth0) already exists
``` 

I will try to figure out a solution.

**Comment by xlgao-zju** [comment]
Do you have any idea on constructing the field `CgroupParent` in `LinuxConfiguration`. `kuberuntime` will do this, but if we test the shim directly, we should construct it before we send the request.

**Comment by xlgao-zju** [comment]
File [k8s/#43890](https://github.com/kubernetes/kubernetes/pull/43890) in order to avoid panic in dockershim when we create pod with empty `NamespaceOption`.

**Comment by xlgao-zju** [comment]
Because we always use default dns options [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L1905), even if I send other options.

So, do not test dns options for now.

/cc @feiskyer @Random-Liu

**Comment by xlgao-zju** [comment]
@feiskyer @Random-Liu This pr is ready for review now. :)

**Comment by Random-Liu** [comment]
> Because we always use default dns options here, even if I send other options.
> So, do not test dns options for now.

I don't understand. Dockershim doesn't generate default dns option. It generates dns option based on `DNSOption` and `DNSSearch` passed, right?

**Comment by Random-Liu** [comment]
Sorry, I get what you mean. Let me see.

**Comment by Random-Liu** [comment]
Filed https://github.com/kubernetes/kubernetes/pull/43925 to fix this.

**Comment by xlgao-zju** [comment]
@Random-Liu Cool

**Comment by xlgao-zju** [comment]
@Random-Liu Add test about DNS options, review plz. :)

**Comment by feiskyer** [comment]
LGTM

**Comment by xlgao-zju** [comment]
@Random-Liu Would you like to take another look?

**Pull request merged**
