### PR TITLE
Responding to comments on #137

### PR DESCRIPTION
**Pull request by mikebrow**
Addresses comments from @Random-Liu on #137.
Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
@Random-Liu per discussion I also removed the two unconfined cases with no additional caps set that were relying on the default caps currently set by docker and containerd.  As discussed we can test out default caps over in a cri-containerd bucket and leave this un-tested for now since the default caps are not specified (currently) in CRI.

**Comment by Random-Liu** [comment]
> per discussion I also removed the two unconfined cases with no additional caps set that were relying on the default caps currently set by docker and containerd. As discussed we can test out default caps over in a cri-containerd bucket and leave this un-tested for now since the default caps are not specified (currently) in CRI.

Thanks! :)

**Comment by Random-Liu** [comment]
LGTM

**Comment by feiskyer** [comment]
LGTM

**Pull request merged**
