### PR TITLE
fix the usage of func Eventually()

### PR DESCRIPTION
**Pull request by Helen-Xie**
Signed-off-by: Helen-Xie <yulinxie@zju.edu.cn>

### CODE REVIEW

**Comment by Helen-Xie** [comment]
ping @feiskyer

**Comment by feiskyer** [comment]
```
[Fail] [k8s.io] Image Manager [It] public image with digest should be pulled and removed [Conformance]
/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/image.go:159
```

This test always failed in my settings. Could you also fix the test?

**Comment by Helen-Xie** [comment]
ok, I will fix it. @feiskyer

**Comment by feiskyer** [comment]
> This test always failed in my settings. Could you also fix the test?

This is caused by old docker versions. Not related with test suite itself.

**Comment by feiskyer** [comment]
LGTM

**Pull request merged**
