### PR TITLE
Switch to vndr

### PR DESCRIPTION
**Pull request by Random-Liu**
Switch to `vndr` and update Kubernetes to https://github.com/kubernetes/kubernetes/commit/5030391c0750eaa3fa7ccdef609ae7b22f29e477

Godep will cause more and more troubles in the future...I've tried `vndr`, and it's actually much better.

@miaoyq I could not update Kubernetes to include mount propagation change, because api packages are not synced properly (Their bots are broken). Let's add mount propagation test after api packages are updated.

@feiskyer

### CODE REVIEW

**Comment by feiskyer** [comment]
Is there any comparison of vndr, [govendor](https://github.com/kardianos/govendor) and [dep](https://github.com/golang/dep)?  seems dep and govendor are more popular.

**Comment by Random-Liu** [comment]
This PR needs more work.

It seems that `critest` want a complete ginkgo in vendor, which `vndr` doesn't support because it only copy in-used package in.

**Comment by mikebrow** [comment]
I need this one to go through so I can add my seccomp test bucket to crit-ools validate, otherwise SeccompProfilePath is not provided through the CRI api. https://github.com/containerd/containerd/pull/1493

**Comment by feiskyer** [comment]
>It seems that critest want a complete ginkgo in vendor, which vndr doesn't support because it only copy in-used package in.

yep, it is required inside the vendor.

@Random-Liu Could you have a try on govendor, which I think is more flexible.

**Comment by mikebrow** [comment]
@Random-Liu try using the -whitelist option. For example:
```
vndr -whitelist github.com/onsi/ginkgo/*
2017/09/12 09:45:56 Collecting initial packages
2017/09/12 09:45:56 Download dependencies
...
2017/09/12 09:53:12 Dependencies downloaded. Download time: 7m13.002535464s
2017/09/12 09:53:12 Collecting all dependencies
2017/09/12 09:53:14 Clean vendor dir from unused packages
2017/09/12 09:53:14 	Ignoring paths matching "github.com/onsi/ginkgo/*"
2017/09/12 09:53:14 WARNING: package github.com/davecgh/go-spew is unused, consider removing it from vendor.conf
2017/09/12 09:53:14 WARNING: package github.com/opencontainers/go-digest is unused, consider removing it from vendor.conf
2017/09/12 09:53:14 Success
2017/09/12 09:53:14 Running time: 7m18.200115614s
```

**Comment by Random-Liu** [comment]
@mikebrow Cool~ Will use whitelist

@feiskyer Let's use `vndr` for now? It's quite simple and can be switched anytime when we think `dep` or `govendor` is better.

**Comment by feiskyer** [comment]
@Random-Liu OK. whitelist seems cool.

**Comment by feiskyer** [comment]
@Random-Liu merge the vendor updates to one commit.

**Comment by Random-Liu** [comment]
@feiskyer Will do.

**Comment by Random-Liu** [comment]
I keep 2 commits:
1) Remove Godep
2) Add `vndr`.

Seems a bit more clear. :)

**Pull request merged**
