### PR TITLE
Grammar in crictl output

### PR DESCRIPTION
**Pull request by ktzee**
Signed-off-by: ktzee <peppe877@gmail.com>

### CODE REVIEW

**Comment by feiskyer** [comment]
@ktzee Thanks of the PR. LGTM.

CI failed because kubernetes required v1.10.2 now. Will merge this after #302.

**Comment by Random-Liu** [comment]
Close and reopen to re-trigger test, not sure whether it works.

**Comment by Random-Liu** [comment]
The CI is still using golang 1.10.1. @ktzee I guess you may need to `git fetch upstream; git rebase upstream/master` and then push again.

**Comment by feiskyer** [comment]
CI green now

/lgtm

**Pull request merged**
