### PR TITLE
Add focus flag

### PR DESCRIPTION
**Pull request by xlgao-zju**
@feiskyer 

Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>

### CODE REVIEW

**Comment by feiskyer** [comment]
Why do we need since we already have `ginkgoFlags`

**Comment by xlgao-zju** [comment]
I think this flag is very useful, so put it out just for convenience.
Feel free to close this PR, if you think it's unnecessary.

**Comment by feiskyer** [comment]
@xlgao-zju Let's close this. Could you add a guide of ginkgoFlags in getting started guide?

**Comment by xlgao-zju** [comment]
Sure.

**Comment by xlgao-zju** [comment]
cc @feiskyer

**Comment by feiskyer** [comment]
LGTM

**Pull request merged**
