### PR TITLE
Cherrypick #339 to release-1.11.

### PR DESCRIPTION
**Pull request by Random-Liu**
I missed cherrypick of #339.

I already manually updated the version for v1.11.1. Cherrypick this to make future release correct.

Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by feiskyer** [comment]
release-1.11 is still using master kubelet for CI. Could you change that to kubernetes release-1.11 in file `hack/install-kubelet.sh`?

**Comment by Random-Liu** [comment]
Sure. Will do in this PR.

**Comment by Random-Liu** [comment]
@feiskyer I decided to do in HEAD first.

We can do better than hard code in the script. :) https://github.com/kubernetes-incubator/cri-tools/blob/release-1.10/hack/install-kubelet.sh#L21

**Comment by feiskyer** [comment]
Yep, +1 for the new method.

**Pull request merged**
