### PR TITLE
Simplify crictl CLI

### PR DESCRIPTION
**Pull request by feiskyer**
This PR simplifies crictl CLI via 

- move subcommands of sandbox/image/container directly to crictl subcommands
- make default output more human readable, e.g. format timestamp and size
- add output format of yaml and json

```
# crictl --help
NAME:
   crictl - client for CRI

USAGE:
   crictl [global options] command [command options] [arguments...]

VERSION:
   0.1.0

COMMANDS:
     info          Display runtime version information
     runs          Run a new sandbox
     stops         Stop a running sandbox
     rms           Remove a sandbox
     inspects      Display the status of a sandbox
     sandboxes     List sandboxes
     create        Create a new container
     start         Start a stopped container
     stop          Stop a running container
     rm            Remove a container
     inspect       Display the status of a container
     ps            List containers
     status        Display status of the container runtime
     attach        Attach to a running container
     pull          Pull an image from a registry
     images        List images
     inspecti      Return the status of an image
     rmi           Remove an image
     exec          Run a command in a running container
     port-forward  Forward local port to a sandbox
     logs          Fetch the logs of a container
     help, h       Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --config value, -c value            Location of the client config file [$CRI_CONFIG_FILE]
   --runtime-endpoint value, -r value  Endpoint of CRI container runtime service (default: "/var/run/dockershim.sock") [$CRI_RUNTIME_ENDPOINT]
   --image-endpoint value, -i value    Endpoint of CRI image manager service [$CRI_IMAGE_ENDPOINT]
   --timeout value, -t value           Timeout of connecting to the server (default: 10s)
   --debug, -D                         Enable debug mode
   --help, -h                          show help
   --version, -v                       print the version
```

See more usage at docs/crictl.md.

### CODE REVIEW

**Comment by xlgao-zju** [comment]
cool! LGTM

**Comment by runcom** [comment]
This is all but simplifying :(

**Comment by runcom** [comment]
@feiskyer can you at least tag a new version of cri-tools?

**Comment by feiskyer** [comment]
@runcom yep, of course, will release later together with kubernetes v1.8

**Pull request merged**
